<?php

namespace ContainerAbd3QxE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessInvitationControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\ProcessInvitationController' shared autowired service.
     *
     * @return \App\Controller\ProcessInvitationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RequestController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ProcessInvitationController.php';

        $container->services['App\\Controller\\ProcessInvitationController'] = $instance = new \App\Controller\ProcessInvitationController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\ProcessInvitationController', $container));

        return $instance;
    }
}
