FROM fundica/php_node:1.7

RUN apt update \
    && docker-php-ext-install pdo pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-enable pdo_mysql

WORKDIR /var/www/html/

RUN curl -sS https://get.symfony.com/cli/installer | bash

# Bundle app source
ADD . /var/www/html/