<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAbd3QxE\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAbd3QxE/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAbd3QxE.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAbd3QxE\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerAbd3QxE\App_KernelTestDebugContainer([
    'container.build_hash' => 'Abd3QxE',
    'container.build_id' => '03431b8b',
    'container.build_time' => 1664119552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAbd3QxE');
