<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNMmxr0V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNMmxr0V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNMmxr0V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNMmxr0V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNMmxr0V\App_KernelDevDebugContainer([
    'container.build_hash' => 'NMmxr0V',
    'container.build_id' => 'cc3935de',
    'container.build_time' => 1664123183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNMmxr0V');
